server:
  port: 18081
spring:
  application:
    name: zdtx
  redis:
    host: 116.198.242.154
    port: 6379
    #    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s